spring:
  datasource:
    username: admin
    url: jdbc:postgresql://localhost:5432/livraria
    platform: postgres
    password: admin
  jpa:
    database: POSTGRESQL
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  database:
    driverClassName: org.postgresql.Driver
server:
  port: '8080'

endpoint:
  cep: https://viacep.com.br/ws/


