spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/b
    platform: postgres
    password: admin
  jpa:
    database: POSTGRESQL
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  database:
    driverClassName: org.postgresql.Driver
server:
  port: '8080'

